version: "3.8"

services:
  coqui-tts:
    image: ghcr.io/coqui-ai/tts-cpu
    container_name: coqui-tts
    ports:
      - "5002:5002"
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "python3 TTS/server/server.py --model_name tts_models/en/vctk/vits"
